// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. Prefer DIRECT_URL;
    // fall back to DATABASE_URL for setups where they're the same.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
